# site name
prefixName: 海染了天空白了什么
siteName: 的blog
# favicon and site master avatar
favicon: /favicon.ico
avatar: /123.jpg
url: http://wt1030.gitee.io/
description: 会一点Java，Python，Golang的一个程序猿小白
cdn: https://cdn.jsdelivr.net/gh/wt325804/BlogImg@1.0
pjax: 1
# 1开启
mathjax: 0

notice: 一个程序猿的个人博客
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    python: {path: /categories/python/, fa: fa-file-text-o }, 
    Golang: {path: /categories/Golang/, fa: fa-file-text-o }, 
    其它: {path: /categories/other/, fa: fa-cloud-download }, 
  } }
  标签: {path: /tags, fa: fa-tags }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /about/, fa: fa-leaf faa-wrench , submenus: { 
  } }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/wt325804/BlogImg@1.0/blog1.jpg
  - https://cdn.jsdelivr.net/gh/wt325804/BlogImg@1.0/blog2.jpg
  - https://cdn.jsdelivr.net/gh/wt325804/BlogImg@1.0/blog3.jpg
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Python, desc: Python, img: /python.jpg}
  - {url: /, title: Golang, desc: Golang, img: /go.jpg}
  - {url: /, title: Java, desc: Java, img: /java.jpg}



# your site build time or founded date
siteBuildingTime: 07/17/2018

#social  url, img PC端配置
social:
  github: {url: https://github.com/wt325804/BlogImg, img: /github.png}
  gitee: {url: https://gitee.com/WT1030/wt1030, img: /gitee.ico}
  wechat: {url: /#, qrcode: /wechat.jpg, img: /wechatlogo.jpg}
  qq: {url: /#, qrcode: /qq.jpg, img: /qqlogo.jpg}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 6703277225
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

# https://github.com/chriskempson/tomorrow-theme
highlight:
  background: '#2d2d2d'
  currentLine: '#393939'
  selection: '#515151'
  foreground: '#cccccc'
  comment: '#999999'
  red: '#f2777a'
  orange: '#f99157'
  yellow: '#ffcc66'
  green: '#99cc99'
  aqua: '#66cccc'
  blue: '#6699cc'
  purple: '#cc99cc'

search:
  path: search.xml
  field: post